/*Ejercicio 1: Verificar el Nit*/



/*Ejercicio 2: Verificar un codigo postal*/

/*Ejercicio 3: Verificar un formato de correo electronico*/

/*Ejercicio 4: Verificar un numero de telefono*/

/*Ejercicio 5: Verificar una dureccion de URL*/

/*Ejercicio 6: Verificar un nombre de usuario*/

/*Ejercicio 7: Verificar una direccion IP*/

/*Ejercicio 8: Verificar un formato de fecha*/

/*Ejercicio 9: Verificar una contraseña segura*/